repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: 'Formatador de fonte com flake8'
        entry: flake8 --exclude venv --show-source --statistics --tee
        language: python
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        description: 'Update requirements.txt with freeze'
        entry: pip freeze > requirements.txt; git add requirements.txt
        language: system
        pass_filenames: false
        stages: [pre-commit]

