repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: 'Formatador de fonte com flake8'
        entry: bash -c './venv/Scripts/flake8 --exclude venv --show-source --statistics --tee'
        language: python
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        description: 'Update requirements.txt with freeze (Windows)'
        entry: bash -c './venv/Scripts/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        description: 'Execute tests with pytest'
        entry: bash -c './venv/Scripts/pytest -v -s'
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

